// Code generated by MockGen. DO NOT EDIT.
// Source: ../../internal/integration/commissionquote/type.go
//
// Generated by this command:
//
//	mockgen -source=../../internal/integration/commissionquote/type.go -destination=quoter_mock.go -package=mockcommissionquote
//

// Package mockcommissionquote is a generated GoMock package.
package mockcommissionquote

import (
	commissionquote "commissionquote/internal/integration/commissionquote"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockQuoter is a mock of Quoter interface.
type MockQuoter struct {
	ctrl     *gomock.Controller
	recorder *MockQuoterMockRecorder
	isgomock struct{}
}

// MockQuoterMockRecorder is the mock recorder for MockQuoter.
type MockQuoterMockRecorder struct {
	mock *MockQuoter
}

// NewMockQuoter creates a new mock instance.
func NewMockQuoter(ctrl *gomock.Controller) *MockQuoter {
	mock := &MockQuoter{ctrl: ctrl}
	mock.recorder = &MockQuoterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuoter) EXPECT() *MockQuoterMockRecorder {
	return m.recorder
}

// GenerateQuote mocks base method.
func (m *MockQuoter) GenerateQuote(ctx context.Context, key string, input commissionquote.QuoteRequest) (commissionquote.QuoteResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateQuote", ctx, key, input)
	ret0, _ := ret[0].(commissionquote.QuoteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateQuote indicates an expected call of GenerateQuote.
func (mr *MockQuoterMockRecorder) GenerateQuote(ctx, key, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateQuote", reflect.TypeOf((*MockQuoter)(nil).GenerateQuote), ctx, key, input)
}
